/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClinicHub;

import ClinicHub.Appointment.*;
import ClinicHub.Consultation.*;
import ClinicHub.Emergency.*;
import ClinicHub.Main.MainPanel;
import ClinicHub.Resources.*;
import StaffPortal.LogIn.LogInController;
import StaffPortal.LogIn.LogInFrame;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author joena
 */
public class MainFrame extends javax.swing.JFrame {
       
    MainPanel mp;
                
    public MainFrame(MainPanel mp) {
        this.mp = mp;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        CardLayout cl = (CardLayout) (jPanel2.getLayout());
        jPanel2.add(mp,"Main Panel");
        cl.show(jPanel2, "Main Panel");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ppntmnt = new Util.CustomButton();
        mrgncy = new Util.CustomButton();
        rsrcs = new Util.CustomButton();
        cnslttn = new Util.CustomButton();
        mply = new Util.CustomButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(162, 196, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 4, 94)), "ISUFST Clinic", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("absender", 2, 24), new java.awt.Color(3, 4, 94))); // NOI18N

        ppntmnt.setBackground(new java.awt.Color(173, 232, 244));
        ppntmnt.setBorder(null);
        ppntmnt.setText("Appointment");
        ppntmnt.setBorderColor(new java.awt.Color(2, 62, 138));
        ppntmnt.setColor(new java.awt.Color(173, 232, 244));
        ppntmnt.setColorClick(new java.awt.Color(0, 119, 182));
        ppntmnt.setColorOver(new java.awt.Color(0, 180, 216));
        ppntmnt.setFont(new java.awt.Font("Instruction", 0, 24)); // NOI18N
        ppntmnt.setMargin(new java.awt.Insets(2, 14, -5, 14));
        ppntmnt.setRadius(50);
        ppntmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppntmntActionPerformed(evt);
            }
        });

        mrgncy.setBackground(new java.awt.Color(173, 232, 244));
        mrgncy.setBorder(null);
        mrgncy.setText("Emergency");
        mrgncy.setBorderColor(new java.awt.Color(2, 62, 138));
        mrgncy.setColor(new java.awt.Color(173, 232, 244));
        mrgncy.setColorClick(new java.awt.Color(0, 119, 182));
        mrgncy.setColorOver(new java.awt.Color(0, 180, 216));
        mrgncy.setFont(new java.awt.Font("Instruction", 0, 24)); // NOI18N
        mrgncy.setRadius(50);
        mrgncy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrgncyActionPerformed(evt);
            }
        });

        rsrcs.setBackground(new java.awt.Color(173, 232, 244));
        rsrcs.setBorder(null);
        rsrcs.setText("Resources");
        rsrcs.setBorderColor(new java.awt.Color(2, 62, 138));
        rsrcs.setColor(new java.awt.Color(173, 232, 244));
        rsrcs.setColorClick(new java.awt.Color(0, 119, 182));
        rsrcs.setColorOver(new java.awt.Color(0, 180, 216));
        rsrcs.setFont(new java.awt.Font("Instruction", 0, 24)); // NOI18N
        rsrcs.setRadius(50);
        rsrcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsrcsActionPerformed(evt);
            }
        });

        cnslttn.setBackground(new java.awt.Color(173, 232, 244));
        cnslttn.setBorder(null);
        cnslttn.setText("Consultation");
        cnslttn.setBorderColor(new java.awt.Color(2, 62, 138));
        cnslttn.setColor(new java.awt.Color(173, 232, 244));
        cnslttn.setColorClick(new java.awt.Color(0, 119, 182));
        cnslttn.setColorOver(new java.awt.Color(0, 180, 216));
        cnslttn.setFont(new java.awt.Font("Instruction", 0, 24)); // NOI18N
        cnslttn.setRadius(50);
        cnslttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnslttnActionPerformed(evt);
            }
        });

        mply.setBackground(new java.awt.Color(173, 232, 244));
        mply.setBorder(null);
        mply.setText("tbc");
        mply.setBorderColor(new java.awt.Color(2, 62, 138));
        mply.setColor(new java.awt.Color(173, 232, 244));
        mply.setColorClick(new java.awt.Color(0, 119, 182));
        mply.setColorOver(new java.awt.Color(0, 180, 216));
        mply.setFont(new java.awt.Font("Instruction", 0, 24)); // NOI18N
        mply.setRadius(50);
        mply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnslttn, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(mrgncy, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(ppntmnt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(rsrcs, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(mply, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(ppntmnt, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(mrgncy, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rsrcs, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cnslttn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(mply, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(102, 156, 239));
        jPanel2.setFont(new java.awt.Font("absender", 0, 24)); // NOI18N
        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesActionPerformed

    }//GEN-LAST:event_resourcesActionPerformed

    private void consultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultationActionPerformed

    }//GEN-LAST:event_consultationActionPerformed

    private void emergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyActionPerformed

    }//GEN-LAST:event_emergencyActionPerformed

    private void appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentActionPerformed

    }//GEN-LAST:event_appointmentActionPerformed

    private void ppntmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppntmntActionPerformed
        AppointmentPanel ap = new AppointmentPanel();
        new AppointmentController(ap);
        CardLayout cl = (CardLayout) (jPanel2.getLayout());
        jPanel2.add(ap,"Appointment Panel");
        cl.show(jPanel2, "Appointment Panel");
    }//GEN-LAST:event_ppntmntActionPerformed

    private void mrgncyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrgncyActionPerformed
        EmergencyFrame ef = new EmergencyFrame();
        new EmergencyController(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_mrgncyActionPerformed

    private void rsrcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsrcsActionPerformed
        ResourcesFrame rf = new ResourcesFrame();
        new ResourcesController(rf);
        rf.setVisible(true);
    }//GEN-LAST:event_rsrcsActionPerformed

    private void cnslttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnslttnActionPerformed
        ConsultationFrame cf = new ConsultationFrame();
        new ConsultationController(cf);
        cf.setVisible(true);
    }//GEN-LAST:event_cnslttnActionPerformed

    private void mplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mplyActionPerformed
           LogInFrame loginFrame = new LogInFrame();
           new LogInController(loginFrame);
           loginFrame.setVisible(true); 
    }//GEN-LAST:event_mplyActionPerformed

    public void buttonListener(ActionListener a){
//        emergency.addActionListener(a);
//        appointment.addActionListener(a);
        mply.addActionListener(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public Util.CustomButton cnslttn;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public Util.CustomButton mply;
    public Util.CustomButton mrgncy;
    public Util.CustomButton ppntmnt;
    public Util.CustomButton rsrcs;
    // End of variables declaration//GEN-END:variables
}
